# Generated by Django 3.2.4 on 2021-06-26 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da vaga')),
                ('faixa_salarial', models.CharField(choices=[('0', 'Até 1.000'), ('1', 'De 1.000 a 2.000'), ('2', 'De 2.000 a 3.000'), ('3', 'Acima de 3.000')], max_length=100, verbose_name='Faixa salarial')),
                ('requisitos', models.TextField(max_length=700, verbose_name='Requisitos')),
                ('escolaridade_minima', models.CharField(choices=[('0', 'Ensino fundamental'), ('1', 'Ensino médio'), ('2', 'Tecnólogo'), ('3', 'Ensino Superior'), ('4', 'Pós / MBA / Mestrado'), ('5', 'Doutorado')], max_length=100, verbose_name='Escolaridade mínima')),
                ('data_de_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_de_atualizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização')),
                ('url', models.SlugField(blank=True, editable=False, verbose_name='Url')),
                ('registro_pela_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL, verbose_name='Registro pela empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=None, max_length=30, verbose_name='Nome')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfils',
            },
        ),
    ]
